name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify index.html exists
        run: |
          test -f index.html
          echo "HTML file found."
